# Build settings
markdown: kramdown
highlighter: rouge

relative_permalinks: false

###############
# Site settings
###############
title: VisualDiffer
keywords: "mac,apple,osx,apps,development,macosx,diff,differ,visual,compare,search,regular expression"
favicon: img/favicon.ico

# Show the popup about cookies
cookiesdirective: true

common_links:
 - title: Official site
   link: &official_link https://visualdiffer.com/
 - title: Wiki
   link: &wiki_link https://wiki.visualdiffer.com/
 - title: Bug report, features request
   link: &bugs_link https://bugs.visualdiffer.com/
 - title: X
   link: &x_link https://x.com/visualdiffer
 - title: GitHub
   link: &github_link https://github.com/visualdiffer

header:
  title: VisualDiffer
  subtitle: Wiki
  # must be 128x128
  logo_image: img/logo.png

# Set 'provider' to false to turn analytics off globally
analytics:
  provider: off
  google: 
    tracking_id: 'UA-257181-9'

navigation_links:
 - title: Support
   link: *bugs_link

social_links:
 - label: Twitter
   link: *x_link
   icon_class: fa-x-twitter
 - label: GitHub
   link: *github_link
   icon_class: fa-github

######################
# Application specific
######################

minItemsToShowToc: 2

# Needed only when generate Apple Help
showToggleButton: true

exclude: ['mas', '*.sh', 'params.json']

toc:
# Set 'type' to false to turn toc generation off globally
# Supported types: 'js' or 'plugin'
  type: js
